=== MommeyBodd/Task3XML/src/main/resources/deposits.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns ="http://www.w3.org/2001/XMLSchema"
        xmlns:tns = "http://www.example.com/deposits"
        targetNamespace="http://www.example.com/deposits"
        elementFormDefault="qualified">

    <element name="abstractDeposit" type="tns:AbstractDeposit" abstract="true"/>
    <element name="timeLimitedDeposit" type="tns:TimeLimitedDeposit" substitutionGroup="tns:abstractDeposit"/>
    <element name="timeUnlimitedDeposit" type="tns:TimeUnlimitedDeposit" substitutionGroup="tns:abstractDeposit"/>

    <element name="deposits">
        <complexType>
            <sequence>
                <element ref="tns:abstractDeposit" minOccurs="2" maxOccurs="unbounded"/>
            </sequence>
        </complexType>
    </element>

    <complexType name="AbstractDeposit">
        <sequence>
            <element name="accountId" type="int"/>
            <element name="amount" type="double"/>
            <element name="profit" type="int"/>
        </sequence>
        <attribute name="bankName" type="string" use="required" />
        <attribute name="bankCountry" type="string"/>
    </complexType>

    <complexType name="TimeLimitedDeposit">
        <complexContent>
            <extension base="tns:AbstractDeposit">
                <sequence>
                    <element name="periodInYear" default="OneYear">
                        <simpleType>
                            <restriction base="string">
                                <enumeration value="OneYear"/>
                                <enumeration value="TwoYear"/>
                                <enumeration value="ThreeYear"/>
                                <enumeration value="FourYear"/>
                                <enumeration value="FiveYear"/>
                            </restriction>
                        </simpleType>
                    </element>
                </sequence>
            </extension>
        </complexContent>
    </complexType>

    <complexType name="TimeUnlimitedDeposit">
        <complexContent>
            <extension base="tns:AbstractDeposit">
                <sequence>
                    <element name="minimalAmount" type="double"/>
                </sequence>
            </extension>
        </complexContent>
    </complexType>
</schema>

=== MommeyBodd/Task3XML/src/main/resources/deposits.xml
<?xml version="1.0" encoding="UTF-8"?>
<deposits xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xmlns="http://www.example.com/deposits"
          xsi:schemaLocation="http://www.example.com/deposits  deposits.xsd">

    <timeUnlimitedDeposit bankName = "NationalBankRepublicOfBelarus" bankCountry = "Belarus">
        <accountId>562144</accountId>
        <amount>2390.87</amount>
        <profit>12</profit>
        <minimalAmount>1000.00</minimalAmount>
    </timeUnlimitedDeposit>

    <timeLimitedDeposit bankName = "RZB" bankCountry = "Germany">
        <accountId>456321</accountId>
        <amount>5590.87</amount>
        <profit>11</profit>
        <periodInYear>TwoYear</periodInYear>
    </timeLimitedDeposit>

    <timeUnlimitedDeposit bankName = "NationalSwissBank" bankCountry = "Switzerland">
        <accountId>748589</accountId>
        <amount>1590.87</amount>
        <profit>17</profit>
        <minimalAmount>1500.00</minimalAmount>
    </timeUnlimitedDeposit>

    <timeUnlimitedDeposit bankName = "BelarusBank" bankCountry = "Belarus">
        <accountId>346951</accountId>
        <amount>3590.87</amount>
        <profit>15</profit>
        <minimalAmount>2000.00</minimalAmount>
    </timeUnlimitedDeposit>

    <timeLimitedDeposit bankName = "CentralBank" bankCountry = "Moscow">
        <accountId>564985</accountId>
        <amount>2590.87</amount>
        <profit>10</profit>
        <periodInYear>OneYear</periodInYear>
    </timeLimitedDeposit>


</deposits>
